### ISSUE TITLE
Texas County Data Sources

### ISSUE THREAD

**Issue by vphill** [unt-libraries/portal-leading#1]
Converting this pdf into a tabular (csv or tsv) dataset that can be used in something like R or Pandas would be useful. 

Texas County Population every ten years - https://texasalmanac.com/sites/default/files/images/topics/ctypophistweb2010.pdf

It can be added to this github repository and we will need to add a citation to the source of the data.

**Comment by Hikingpanda68** [comment]
This issue has been accomplished.

**Comment by vphill** [comment]
You might want to look at the County names, 

I believe you are including the superscript footnote references in some of your names. 

Such as `Bandera 1`

In the following lines.

https://github.com/unt-libraries/portal-leading/blob/main/data/formatted_TX_County.csv#L155-L171

Those should be removed from the dataset otherwise you will have a tough time matching up county names as we move forward.

**Comment by Hikingpanda68** [comment]
Hi Mark!

Thanks for your comments. I didn't recognize it before. I am going to fix it now.
