### ISSUE TITLE
create data directory in the untl-bs folder. 

### ISSUE THREAD

**Issue by vphill** [unt-libraries/portal-leading#12]
In the untl-bs folder let's go ahead and create a `data` directory and move the json files we are creating into that directory.  

This way we will have a `code` and a `data` directory to better sort things. 

You can do this in the web-based github but it might be easier with Github Desktop or using the command line. 

If you haven't used git on the command line, I suggest working through this Software Carpentry Lesson - https://swcarpentry.github.io/git-novice/

**Comment by 50jonesh** [comment]
I tried using the command line to make the changes and couldn't get it to work. But I was able to use GitHub desktop with no trouble. I guess I need to practice more using the command line, but at least the new directory is there now!
