### ISSUE TITLE
Write a Solr query to capture the range of occurrence counts of UNTL-BS terms

### ISSUE THREAD

**Issue by 50jonesh** [unt-libraries/portal-leading#13]
I've already done this through edit.texashistory.unt.edu, but the numbers were were not entirely accurate (the Portal filter excludes some records that do display on the Portal). I should replicate that same query using Solr.

**Comment by 50jonesh** [comment]
Running the query is easy, since it's a straightforward request and the URL is almost identical to the one @vphill constructs in "merge-untlbs-json-with-counts.py". And I can easily export the list by either running that script to get a JSON file, or simply copying and pasting plus some reformatting using Excel functions.

But I'd like to practice modifying the script, and try to get it to run the query and print the reformatted list without iterating through untl-bs.json - just to see if I can get it to work, and to get a better understanding of how the code is working.

**Comment by vphill** [comment]
I think this is a good script to modify how you've suggested.  When you get something working you can check it into the repository in the code directory and we can provide any suggestions we might have.

**Comment by 50jonesh** [comment]
So far, all I've been able to get to run is extract-untlbs-counts-2022-09-08.py - which I know is a mess. For one thing, the output isn't formatted in any kind of helpful way, and I know I probably took the most roundabout way to write the output to a file (I'm still new to even the most basic parts of Python).

On a separate but somewhat related note, I found that I actually can't get the original merge-untlbs-json-with-counts.py to run. It tells me that the "exit()" command under the first "if" statement is not defined. Do you know why it might be doing that?
