### ISSUE TITLE
Turn collocation counts into percentages

### ISSUE THREAD

**Issue by 50jonesh** [unt-libraries/portal-leading#16]
Is there a way for me to generate collocation counts as _percentages_ of a term's total occurrence count, rather than as straight numbers? That would help me identify the top most-collocated pairs across the entire Portal much more easily.

(Does the fact that, when querying in Solr, the UNTL-BS term being queried always appears as the top value in the facet list help at all? Is there a way of automatically dividing the collocation count for each other term by the count on the first term in the list?)

**Comment by vphill** [comment]
Here is how I would start to approach this. 

First we need to create a file that contains the total number of records that each subject is present in.  If we are only interested in collocations for the UNTL-BS that isn't a very long list.  If we are interested in all subjects that's a much larger list.  That output list can be cached locally and used as a quick lookup for the total number of records that have that subject. 

The second piece would be to write a script that loads the total number cached file for quick lookup.  We would then identify a single UNTL-BS we want to investigate.  We would do our solr query to get the subjects that occur alongside our specified UNTL-BS and then divide the number of records that these subjects are present with (the collocation) by the total instances in all of the Portal from that cached file.  Finally, we can also output the total count and the collocated count just so we have all of the values. 

As an example, for the UNTL-BS of `"Government and Law - Elected Officials - Presidents"` has 14,117 subject values it is collocated with in the Portal. Here are some of the most frequent with their values and record counts.:

```
Government and Law - Elected Officials - Presidents     7826
Business, Economics and Finance - Communications - Media        6648
news stories    6582
news segments   5662
scripts 5052
Television broadcasting of news.        4610
Nixon, Richard  3601
Television broadcasting of news 1423
video footage   985
video clips     984
Television news programs        981
Government and Law - Elected Officials - Senators       890
Social Life and Customs - Meetings and Conferences      838
Government and Law - Money      746
Military and War - Wars - Vietnam War   685
Government and Law - Politics - Speeches        577
Government and Law - Politics   567
Johnson, Lyndon B.      494
People - Groups 358
interviews      348
Government and Law - Elected Officials - Congress       339
Government and Law - Elected Officials - Governors      333
Government and Law - Elected Officials - Vice Presidents        315
Government and Law - Vital Records - Deaths     315
Reagan, Ronald  315
Social Life and Customs - Clubs and Organizations       310
protests        282
Business, Economics and Finance - Transportation - Aviation - Airplanes 280
Johnson, Lyndon Baines, Pres. U.S., 1908-1973.  275
Government and Law - Law Enforcement - Investigations   269
Government and Law - Law Enforcement - Police   237
elections       231
```

The output we get with the process described above might be:

```
Government and Law - Elected Officials - Presidents     100.0   7826    7826
Business, Economics and Finance - Communications - Media        2.7119086566506625      245141  6648
news stories    2.962609544986024       222169  6582
news segments   2.7060223574224445      209237  5662
scripts 3.9710737305455117      127220  5052
Television broadcasting of news.        2.56212172579184        179929  4610
Nixon, Richard  75.39782244556113       4776    3601
Television broadcasting of news 8.369111333294125       17003   1423
video footage   1.1403498616529864      86377   985
video clips     1.1457181114280723      85885   984
Television news programs        1.150868137024871       85240   981
Government and Law - Elected Officials - Senators       15.363369583980665      5793    890
Social Life and Customs - Meetings and Conferences      3.6788269897712804      22779   838
Government and Law - Money      5.792824972821867       12878   746
Military and War - Wars - Vietnam War   14.09755093640667       4859    685
Government and Law - Politics - Speeches        12.440707201379904      4638    577
Government and Law - Politics   5.499515033947624       10310   567
Johnson, Lyndon B.      53.69565217391305       920     494
People - Groups 1.6124673452842087      22202   358
interviews      1.1648925487045592      29874   348
Government and Law - Elected Officials - Congress       15.945437441204138      2126    339
Government and Law - Elected Officials - Governors      7.317073170731707       4551    333
Government and Law - Elected Officials - Vice Presidents        28.276481149012568      1114    315
Government and Law - Vital Records - Deaths     3.1620156595061233      9962    315
Reagan, Ronald  36.12385321100918       872     315
Social Life and Customs - Clubs and Organizations       0.9757325863208587      31771   310
protests        8.17628298057408        3449    282
Business, Economics and Finance - Transportation - Aviation - Airplanes 3.19926873857404        8752    280
Johnson, Lyndon Baines, Pres. U.S., 1908-1973.  81.12094395280236       339     275
Government and Law - Law Enforcement - Investigations   2.1388248389918103      12577   269
Government and Law - Law Enforcement - Police   1.1721647954893912      20219   237
elections       5.006501950585176       4614    231
```

If we sorted those 32 collocated terms by the second column, which is the percentage of total instances, we would get something like this. 

```
Government and Law - Elected Officials - Presidents	100.0	7826	7826
Johnson, Lyndon Baines, Pres. U.S., 1908-1973.	81.12094395280236	339	275
Nixon, Richard	75.39782244556113	4776	3601
Johnson, Lyndon B.	53.69565217391305	920	494
Reagan, Ronald	36.12385321100918	872	315
Government and Law - Elected Officials - Vice Presidents	28.276481149012568	1114	315
Government and Law - Elected Officials - Congress	15.945437441204138	2126	339
Government and Law - Elected Officials - Senators	15.363369583980665	5793	890
Military and War - Wars - Vietnam War	14.09755093640667	4859	685
Government and Law - Politics - Speeches	12.440707201379904	4638	577
Television broadcasting of news	8.369111333294125	17003	1423
protests	8.17628298057408	3449	282
Government and Law - Elected Officials - Governors	7.317073170731707	4551	333
Government and Law - Money	5.792824972821867	12878	746
Government and Law - Politics	5.499515033947624	10310	567
elections	5.006501950585176	4614	231
scripts	3.9710737305455117	127220	5052
Social Life and Customs - Meetings and Conferences	3.6788269897712804	22779	838
Business, Economics and Finance - Transportation - Aviation - Airplanes	3.19926873857404	8752	280
Government and Law - Vital Records - Deaths	3.1620156595061233	9962	315
news stories	2.962609544986024	222169	6582
Business, Economics and Finance - Communications - Media	2.7119086566506625	245141	6648
news segments	2.7060223574224445	209237	5662
Television broadcasting of news.	2.56212172579184	179929	4610
Government and Law - Law Enforcement - Investigations	2.1388248389918103	12577	269
People - Groups	1.6124673452842087	22202	358
Government and Law - Law Enforcement - Police	1.1721647954893912	20219	237
interviews	1.1648925487045592	29874	348
Television news programs	1.150868137024871	85240	981
video clips	1.1457181114280723	85885	984
video footage	1.1403498616529864	86377	985
Social Life and Customs - Clubs and Organizations	0.9757325863208587	31771	310
```

You would then use the script to look at any of the UNTL-BS values you were interested in investigating.  

Let me know if this is what you were thinking and I can put together the example scripts I used for this.

**Comment by 50jonesh** [comment]
Thanks!

Actually, this is actually kind of the reverse of what I was thinking. Where you’ve calculated each term’s collocation count as a percentage of _its own_ total, I was thinking of calculating their collocation counts as a percentage of the _target term’s_ total (so, in this case, 7826 for “Government and Law - Elected Officials – Presidents”).

But, now that I see this, I realize that what would be more effective is a comparison between the two numbers. For example, being able to say that “Business, Economics and Finance - Communications – Media” is collocated on 84.95% of the records that have “Government and Law - Elected Officials – Presidents” seems to suggest a high correlation between the two terms - but knowing that these records constitute only 2.71% of “Media”’s total occurrences helps clarify that it’s rather one-sided, and is more related to the overuse of “Media” than a true semantic connection between the two terms. Similarly, knowing that “Johnson, Lyndon Baines, Pres. U.S., 1908-1973” is collocated on only 3.5% of records with “Government and Law - Elected Officials – Presidents” but that that corresponds to 81.12% of the LBJ records says a lot more than either number alone could.

Is there a way to produce and export both numbers using a similar method to what you’ve done here? If so, this could prove very helpful not only for Question 1 Approach B (simply mapping out the relationships among terms in the schema), but also for Question 2 (identifying where overuse has led terms to be useless for browsing).

And, since I know that these lists will get very long very fast, is it possible to limit the number of terms returned to the top 10 or 20 most collocated results? I know this is possible in a Solr Query, so I presume it would be possible to build such a limiter into a script that’s running them, right?

**Comment by 50jonesh** [comment]
Hi @vphill - would you be able to share the scripts you used to do the above? I'd like to see if I can figure out how to make the changes I mentioned. Thanks!

**Comment by vphill** [comment]
Just wanting to verify this is what we are after. 

In the data presented below we have data for target term `Agriculture`

First column is the collocation term, the second is the number of records that term is present in over the whole Portal.  The third value is the number of instances collocated with the target term (Agriculture in this case) the fourth column is the percentage based on the whole Portal counts and the collocation counts and the fifth is the percentage of records within the  records with the target term that also have the collocated term. 

```
Agriculture     2800    2800    100.0   100.0
Business, Economics and Finance - Communications - Newspapers   866716  1184    0.13660760848997827     42.285714285714285
Business, Economics and Finance - Journalism    855982  1178    0.13761971630244563     42.07142857142857
Business, Economics and Finance - Advertising   861666  1177    0.13659585036429428     42.035714285714285
Agriculture -- Texas -- Newspapers.     1003    976     97.30807577268196       34.85714285714286
Places - United States - Texas - Limestone County       2517    713     28.327373857767185      25.46428571428571
Limestone County (Tex.) -- Newspapers.  1996    712     35.671342685370746      25.428571428571427
Mexia (Tex.) -- Newspapers.     1988    712     35.8148893360161        25.428571428571427
Mexia (Tex.) -- Periodicals.    1888    712     37.71186440677966       25.428571428571427
Landscape and Nature - Geography and Maps       85338   392     0.45934987930347554     14.000000000000002
Science and Technology  21039   384     1.825181805218879       13.714285714285715
Patents -- Texas.       17435   319     1.829652996845426       11.392857142857144
Czechs -- Texas -- Newspapers.  7145    263     3.680895731280616       9.392857142857142
Halletsville (Tex.) -- Newspapers.      263     263     100.0   9.392857142857142
Halletsville (Tex.) -- Periodicals.     263     263     100.0   9.392857142857142
Lavaca County (Tex.) -- Newspapers.     12454   263     2.111771318451903       9.392857142857142
Places - United States - Texas - Lavaca County - Hallettsville  4523    263     5.81472474021667        9.392857142857142
Business, Economics and Finance - Communications - Media        248641  226     0.09089410032939056     8.071428571428571
news stories    224858  214     0.09517117469691984     7.642857142857143
news segments   211925  205     0.09673233455231803     7.321428571428572
scripts 128962  161     0.12484297700097703     5.75
Halletsville    2057    152     7.3894020418084585      5.428571428571429
Government and Law - Texas Laws and Regulations 33088   151     0.45635880077369445     5.392857142857143
Bills, Legislative -- Texas.    14429   143     0.991059671494906       5.107142857142858
State and local government operations   14361   143     0.9957523849314115      5.107142857142858
Texas -- Politics and government.       14444   143     0.9900304624757685      5.107142857142858
Business, Economics and Finance 14099   140     0.9929782254060571      5.0
Government and Law      11923   112     0.9393608991025749      4.0
Abilene (Tex.) -- Newspapers.   17468   100     0.572475383558507       3.571428571428571
Abilene (Tex.) -- Periodicals.  7949    100     1.258019876714052       3.571428571428571
```

**Comment by vphill** [comment]
To generate this data you would run the following script `generate-subject-total-values-json.py` (in the `code` folder).  
https://github.com/unt-libraries/portal-leading/blob/main/untl-bs/code/generate-subject-total-values-json.py

`python3 ./code/generate-subject-total-values-json.py > ./data/all-subject-instance-counts-2022-11-09.json`

That will get you the total instance count. 

Next you run the script `collocations-as-percentages.py` with the data from the previous output.
https://github.com/unt-libraries/portal-leading/blob/main/untl-bs/code/collocations-as-percentages.py

`python3 ./code/collocations-as-percentages.py ./data/all-subject-instance-counts-2022-11-09.json "Business, Economics and Finance - Communications - Newspapers"`

**Comment by 50jonesh** [comment]
YES, this is exactly what I’m looking for!

However, I’m having trouble following what’s happening in the code. I can follow along with “generate-subject-total-values-json.py” well enough, and I can get the same JSON output file you uploaded. But I think I’m missing something when it comes to running “collocations-as-percentages.py” with that JSON output. I didn’t get a discrete file from the script, and I also can’t see where the second script actually utilizes the JSON file, except to reference it in a printed message. I was hoping I could piece together more, but I keep getting a name error that “exit” is not defined, so I can’t fiddle around much to try and understand what’s happening further down in the script. I don’t know if its something to do with the fact that I’m using Spyder, or if it’s something incredibly obvious that’s just the result of my ignorance of Python.

I would try just looking at the output file you’ve pointed to in your comment, but I don’t quite understand that either. I assume that the strings you’ve designated as “code” in your comment above are referencing the file location of the python script and the output JSON files in the repository, right? If so, I don’t understand what that second one means. Isn’t “./data/all-subject-instance-counts-2022-11-09.json” just the same output from the previous script? And “Business, Economics and Finance - Communications - Newspapers" doesn’t look like part of a filename – are you just referencing that one line in the .json file?

**Comment by vphill** [comment]
You might be getting tripped up on the paths and locations of the files.  Assuming you are in the root directory of the untl-bs folder for this repo, `./code/` is a relative path to the code folder and `./data/` is a relative path to the data folder.  In the first part we are redirecting the output of the file into a .json file because the output of the `generate-subject-total-values-json.py` is json.  If you removed the `> ./data/all-subject-instance-counts-2022-11-09.json` portion it would just print to your screen as output. 

The second script is just demonstrating how you would run it if you again were in the untl-bs folder of this repository.  The first argument is the location of the file you just created in the previous step.  The second argument is the UNTL-BS you are interested in looking at collocations for.  It could have been `Agriculture` I just wanted to demonstrate how you would do it for the ones with spaces in the subject. 

If you want to paste in the errors you are getting into Slack I can give you a better idea of what is going on.

**Comment by 50jonesh** [comment]
I realize what was confusing me now – and I’m pretty embarrassed to admit it. I didn’t realize that you were running the script from the command line, and that this was a command line prompt. I was running the scripts in Spyder, and wondering what the command prompt was even referring to. I was also confused because I wasn’t getting an output file by running the script, just like you said. I should be able to actually run it now.
