### ISSUE TITLE
Texas Library List

### ISSUE THREAD

**Issue by vphill** [unt-libraries/portal-leading#2]
I think it make sense to use the [2019-All](https://www.tsl.texas.gov/sites/default/files/public/tslac/ld/ldn/accreditation/statistics/2019CentralStatistics2.xlsx) dataset for our work. 

This is from the TSLAC Public Library Accreditation and Statistics program - https://www.tsl.texas.gov/ldn/statistics

I suggest we create a thinner tabular dataset (tsv or csv) for use with R or Pandas. 

With a quick look I could see the fields of

* Library Name
* Population of the Legal Service Area
* Legal Establishment
* Region?
* County 

All being the most important with the County being the field that we will use to match this against our other datasets.

This can go into this repository with a citation to the datasets that we used.

**Comment by Hikingpanda68** [comment]
[Texas Library List.xlsx](https://github.com/unt-libraries/portal-leading/files/6799969/Texas.Library.List.xlsx)

I just tried to create the dataset as required.

**Comment by vphill** [comment]
This is a good start. 

I would suggest that we try and use text based formats such as tab delimited or comma-separated values for the datasets we are building. 

I've added a `data` folder that you can use to upload the resulting dataset.  I suggest a title without space such as `texas-library-list.csv` for a comma-seperated values version. 

You should some information into the `README.md` about how this dataset was created and a citation to the original dataset.

**Comment by Hikingpanda68** [comment]
I see. I will go on to convert it to a tidy dataset.
