### ISSUE TITLE
Topic Model Dataset Creation

### ISSUE THREAD

**Issue by vphill** [unt-libraries/portal-leading#22]
We need to create datasets for the following UNTL-BS fields.  (supplied below by @50jonesh 

We want to have tab delimited with 

aubrey_identifier
display_title
dc_description
dc_subject

We know that there will be an uneven number of columns per row across the dataset and that shouldn't cause issue for the topic modeling. 

We will give Mallet a shot first for topic modeling - https://mimno.github.io/Mallet/topics.html

**Comment by 50jonesh** [comment]
Below are the 22 terms that I've identified as prime candidates for topic modeling. They are terms that either my spread vs. usage analysis identified as having proportionally more occurrences than narrower terms, or that my outlier analysis identified as having an abnormally high number of occurrences overall, and they've passed the test of parent/child collocation. It remains to be seen, though, whether they will pass the metadata variability test.

[TermsOfInterest.txt](https://github.com/unt-libraries/portal-leading/files/9719247/TermsOfInterest.txt)

**Comment by 50jonesh** [comment]
I've generated text documents for 16 of these 22 terms (the remaining 6 had over 100,000 occurrences in the Portal). They can be found in the "TopicModeling" folder.
