### ISSUE TITLE
Texas Newspapers from Chronicling America

### ISSUE THREAD

**Issue by vphill** [unt-libraries/portal-leading#3]
Chronicling America maintains a list of a large number of newspaper titles from around the US

https://chroniclingamerica.loc.gov/search/titles/

You can limit to the 5,863 titles that they have records of from Texas  - https://chroniclingamerica.loc.gov/search/titles/results/?state=Texas

by adding a `format=json` to the URL you can get a json dataset that can try to use for our work.
https://chroniclingamerica.loc.gov/search/titles/results/?state=Texas&format=json

We can also adjust the number of rows in the results and the page that we are on. 
https://chroniclingamerica.loc.gov/search/titles/results/?state=Texas&rows=100&format=json&page=1
https://chroniclingamerica.loc.gov/search/titles/results/?state=Texas&rows=100&format=json&page=2

One of the things to keep in mind when working with these kinds of systems is to "not be greedy" for example, we have 5863 titles to grab from this.  A greedy option would be to try and adjust rows=5863 and try and grab everything in one request.  This may be just fine, but it also may be an unplanned sort of request in their system.  

I will generally try and break this kind of request into a shorter set of requests,  say 100 or maybe 250 per request and then just do a sequence of requests with a few seconds waiting between the requests.  It might take a few minutes on my end but usually won't make the data providers upset because someone is hammering on a system when they don't need to. 

It will be good to have the output finally end up in a tabular (tsv or csv) form that we can use in R or Pandas.  We will need to do a bit of processing to get the info we are wanting.  Just a quick look I think we might want

* Title
* LCCN (this is the unique identifier for these titles in this system, very useful)
* start_year
* end_year
* frequency
* language
* place

You will also want to do some work with the `place` field in the records to try and extract the "County" for each titles so that we can have things align. 

I suggest creating a directory in the repository called `newspaper-titles` and include both the dataset as well as any scripts used in making the final tabular dataset from the json. 

One final suggestion, I suggest downloading the data as .json files and then writing any tools/scripts for working with the data to work off of those files as input instead of trying to have the script do the requests from the database.  Just a suggestion.

**Comment by cozettec** [comment]
[Task3_Texas-Newspapers-from-Chronicling-America.xlsx](https://github.com/unt-libraries/portal-leading/files/6917306/Task3_Texas-Newspapers-from-Chronicling-America.xlsx)
[README task3 (leading).docx](https://github.com/unt-libraries/portal-leading/files/6917312/README.task3.leading.docx)

While cleaning in OpenRefine, I wasn't sure how (or if) we wanted to merge some of the values in the "frequency", "place", and "language" variables. Maybe we can discuss this on Wednesday? Or if you have any ideas / guidance prepared, I'd be happy to wrap this up before our meeting Wednesday. Please see the README file for a list of the values (in the "frequency" variable) that I did merge. Thanks!

**Comment by cozettec** [comment]
Please see the revised README file for task3 recoding revisions 
[Task3_Recode_README_202108.docx](https://github.com/unt-libraries/portal-leading/files/7032071/Task3_Recode_README_202108.docx)
