### ISSUE TITLE
Texas County dataset

### ISSUE THREAD

**Issue by vphill** [unt-libraries/portal-leading#4]
Should be pretty straightforward. 

We need a tabular (tsv or csv) file listing the 254 counties in Texas, along with a few other bits of data. 

I suggest we include the following

- County Name (with 'County' added to the end like Denton Count)
- FIPS Code 
- geonames ID
- wikidata ID
- UNTL Place Name String
-  UNTL County String (see note)

**Note**:  You can verify against this page - https://texashistory.unt.edu/search/?q=&t=fulltext&sort=added_d&fq= then go to the county facet and type "TX".  It should get you how the Texas county is represented in this system (Aubrey). 

This can get added to the github repository

**Comment by vphill** [comment]
@akrahmer what is this thing.

**Comment by cozettec** [comment]
[Task4_Texas-Counties-Dataset.xlsx](https://github.com/unt-libraries/portal-leading/files/6892831/Task4_Texas-Counties-Dataset.xlsx)
[README (Task4).docx](https://github.com/unt-libraries/portal-leading/files/6892834/README.Task4.docx)

**Comment by cozettec** [comment]
I know the .xlsx needs to be a .csv (.tsv), but I'm not sure how to upload the .csv file here...
