### ISSUE TITLE
Texas Digital Newspaper Program - Issues by County and Decade dataset

### ISSUE THREAD

**Issue by vphill** [unt-libraries/portal-leading#5]
The following URL shows the Solr output of the Texas Digital Newspaper Program (TDNP)

https://digital.library.unt.edu/solrparse/raw/?q=*:*&fq=untl_collection:TDNP&fq=str_location_state:Texas&facet=true&rows=0&facet.pivot.mincount=1&facet.pivot=str_location_county,untl_decade&facet.limit=-1

This can be parsed into a tabular dataset that we can use for further analysis. 

While _most_ of the values are going to be Texas counties, they should be checked because there is also the possibility that non-Texas county information could be included.

**Comment by Hikingpanda68** [comment]
I tried to clean the data and changed it to a CSV file. The dataset and my code has been uoloaded. Please take a look.
