### ISSUE TITLE
Portal to Texas History Photographic Dataset - Items by County and Decade

### ISSUE THREAD

**Issue by vphill** [unt-libraries/portal-leading#6]
Similar to #5, this URL provides the Solr output from the Portal related to photographs held. 

https://digital.library.unt.edu/solrparse/raw/?q=(aubrey_system:PTH%20OR%20untl_institution:UNTA)%20AND%20dc_rights_access:public&fq=dc_type:image_photo&&facet=true&rows=0&facet.pivot.mincount=1&facet.pivot=str_location_county,untl_decade&facet.limit=-1&&fq=str_location_state:Texas

This should be converted into a tabular data format that can be used for subsequent analysis. 

It should be noted that there are going to be non-Texas counties represented in this data so they will need to be removed for the final dataset because we are focusing on Texas.

**Comment by Hikingpanda68** [comment]
I converted the data as required and uploaded it to the data file. Please take a look.
